package com.example.Task.Spring.Web.and.MySQL;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This mean that this is the controller
@RequestMapping(path="/demo") // This class will activate with /demo route
public class MainController {
	
	@Autowired // Calling bean called userRepository, which will 
			   // be auto-generated by spring and used to handle data
	private UserRepository userRepository;
	
	@PostMapping("/add") // End point for post method
	public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "User has been saved";
	}
	// @ResponseBody mean that return string is response
	// @RequestParam means requested parameter for GET or POST method
	
	@GetMapping("/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// Returns JSON or XML
		return userRepository.findAll();
	}
	
	
	@DeleteMapping("/user/{id}")
	public @ResponseBody String delete(@PathVariable Integer id){
		userRepository.deleteById(id);
		return "User has been deleted";
	}
}
